DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS grocery;

CREATE TABLE post
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE grocery
(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    subject TEXT NOT NULL,
    content TEXT NOT NULL,
    date DATETIME NOT NULL
);